image:
  repository: timothyjmiller/prisma-studio
  tag: latest
  pullPolicy: Always

replicaCount: 1

database:
  type: postgresql
  port: 5432

  # The following configs accept the Container Env Spec form This applies for `host`, `user`, `name`, and `password`
  # Using `password` as an example you can directly specify the value:

  # password:
  #   value: ""

  # Or we can specify the value from a secret or other reference points
  # password:
  #   valueFrom:
  #     secretKeyRef:
  #       name: ""
  #       key: ""
  host:
  user:
  name:
  password:

service:
  type: ClusterIP
  port: 5555
  targetPort: 5555
  protocol: TCP

resources:
  requests:
    cpu: 20m
    memory: 55M

probes:
  liveness:
    path: /
    initialDelaySeconds: 5
    timeoutSeconds: 2
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
  readiness:
    path: /
    initialDelaySeconds: 2
    timeoutSeconds: 2
    periodSeconds: 5
    successThreshold: 1
    failureThreshold: 3
